name: Certification checker CI

"on":
  schedule:
    # Daily
    - cron: "23 7 * * *"
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  nox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Inputs:
          #   session: name of session
          #   python-versions: comma-separated list of Python versions to install
          #   extra-args (optional): extra arguments to pass to nox session.
          - session: "actionlint"
            python-versions: "3.12"
            extra-args: ""
          - session: "zizmor"
            python-versions: "3.12"
            extra-args: ""
    name: "Run nox ${{ matrix.session }} session"
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup nox
        uses: wntrblm/nox@2026.02.09
        with:
          python-versions: "${{ matrix.python-versions }}"
      - name: "Run nox -e ${{ matrix.session }}"
        # zizmor: ignore[template-injection]
        run: |
          nox -e "${{ matrix.session }}" -- ${{ matrix.extra-args }}

  check:
    if: always()

    needs:
      - nox

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
