---
# This workflow runs the reusable workflow
# in this repository for testing purposes.
name: Test certification-reusable workflow

permissions:
  contents: read

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

concurrency:
  group: test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  call:
    uses: ./.github/workflows/certification-reusable.yml
